### ISSUE TITLE
新版的绑定数据源速度比旧版的慢好多啊

### ISSUE THREAD

**Issue by Lsy1992** [YoKeyword/IndexableRecyclerView#21]
查看适配器中设置数据的方法没有开线程啊
 /**
     * @param callback Register a callback to be invoked when this datas is processed.
     */
    public void setDatas(List<T> datas, IndexCallback<T> callback) {
        this.mCallback = callback;
        mDatas.clear();
        mDatas.addAll(datas);
        notifyInited();
    }

这样加载数据6000多条， 同样的功能方法用旧版1~2秒就填充完毕了，新版等待了起码5~6秒，怎么办啊？

**Comment by YoKeyword** [comment]
线程是在 notifyInited() －>  IndexableLayout的 451行，单线程的线程池开启的，排序等初始化数据的操作是在这里面开始的~  

不过你说的问题我研究下，  5-6秒 是阻塞了主线程？

**Comment by Lsy1992** [comment]
是的，很卡哦

**Comment by YoKeyword** [comment]
我这边试验了下， 原来的版本的8倍数据1秒多点，现在版本11秒；

确实慢了很多，暂时猜测是排序规则，精确到所有字的拼音，不再是数据源的首字母排序～

另外主线程没被阻塞啊～

**Comment by Lsy1992** [comment]
\(^o^)/~ 大兄弟着咋办呢，我现在不知道怎么改...

**Comment by YoKeyword** [comment]
不要慌 ＝。＝  我先把排序规则按原版本试下～

**Comment by Lsy1992** [comment]
劳烦了，静候佳音

**Comment by YoKeyword** [comment]
是这个原因， 用原来的PinyinComparator：只比对第一个字的首字母，就和之前一样快了～

我提供个API，可选择默认的排序规则吧～  默认是全拼音排序

**Comment by Lsy1992** [comment]
恩只能是优先性能方面了，全拼音影响的大概也就是索引条，直接搜索的话是根据文本查的。如果用了全拼音性能下降了好多，体验不好啊。

**Comment by YoKeyword** [comment]
会提供2种排序规则，首字母 和 全拼

因为选择城市里 有300多条数据  初始化的话不到1秒就初始化完成了～

所以我觉得速度还行～    你觉得**默认**排序规则是首字母的比较好吗？

**Comment by Lsy1992** [comment]
这样看起来没有那么奇怪

**Comment by YoKeyword** [comment]
````java
// 快速排序。  排序规则设置为：只按首字母  （默认全拼音排序）  效率很高，是默认的10倍左右。  按需开启～
indexableLayout.setFastCompare(true);
````
已经更新1.0.3版本啦～

**Comment by Lsy1992** [comment]
这么快...我刚把旧版的导进去

**Comment by YoKeyword** [comment]
现在 在setDatas()之前调用
indexableLayout.setFastCompare(true);

就和以前一样快啦～

**Comment by Lsy1992** [comment]
多谢多谢
