### ISSUE TITLE
header的数据改变了，怎么更新

### ISSUE THREAD

**Issue by wii-huxley** [YoKeyword/IndexableRecyclerView#23]
改变header的数据，实现起来有点困难

**Comment by YoKeyword** [comment]
调用下面的方法
`headerAdapter.notifyDataSetChanged();`

**Comment by wii-huxley** [comment]
数据传不进去，调用了也没有什么用吧

**Comment by YoKeyword** [comment]
没明白， 你可以看下PickCityActivity，“定位中” 刷新数据的 代码

**Comment by wii-huxley** [comment]
删除不行吧

**Comment by YoKeyword** [comment]
删除header内的数据可以，移除整个headerView的功能todo

**Comment by wii-huxley** [comment]
删除不行吧

**Comment by wii-huxley** [comment]
删除不行吧

**Comment by wii-huxley** [comment]
删除不行吧

**Comment by wii-huxley** [comment]
调用data.get(position).setName()，再调用notifyDataSetChanged()可以更新，
应该时因为对象引用的关联吧，
但是data.clear（）（或者data.add(obj)），再调用notifyDataSetChanged()并不能更新

**Comment by YoKeyword** [comment]
嗯 确实有这个问题，稍后会解决这个问题  感谢反馈啦

**Comment by wii-huxley** [comment]
还有一个问题，IndexableLayout onDataChanged()中post()方法不能百分之百执行
http://blog.5ibc.net/p/28158.html
为什么不使用post(),数据更新就会有问题？

**Comment by YoKeyword** [comment]
感谢  post的问题 现在添加了安全的getSafeHandler()的post方式  ：）
文章里详细的从源码分析了原因

**Comment by YoKeyword** [comment]
已经push了 1.0.5

添加
`indexableLayout.removeHeaderAdapter()`,  `indexableLayout.removeFooterAdapter();`

 `header/footerAdapter.addData()`,  `header/footerAdapter.removeData()`

addData(int position, data)等方法 因当前代码结构实现较繁琐，回头有空再更新～
