### ISSUE TITLE
如何不使用tinypinyin

### ISSUE THREAD

**Issue by icyfox-bupt** [YoKeyword/IndexableRecyclerView#25]
数据源中已经根据拼音分类好了
如何不使用拼音库减少包大小

**Comment by YoKeyword** [comment]
暂时没有没提供该方法， 不过TinyPinyin的库非常非常小，不必在意这点库的大小～

另外你的情况可以使用：
````java
// 排序规则设置为：只按首字母  （默认全拼音排序,false）  效率很高，是默认的10倍左右。
indexableLayout.setFastCompare(true);
````

**Comment by YoKeyword** [comment]
刚刚push 1.0.7：
setFastCompare() 被标记为过时方法～
可以使用 setCompareMode(@CompareMode int mode)代替：
你的场景可以使用`indexableLayout.setCompareMode(IndexableLayout.MODE_NONE)`（字母模块内不排序）来提升性能
