### ISSUE TITLE
IndexableLayout中有一行冗余代码

### ISSUE THREAD

**Issue by JackChen1999** [YoKeyword/IndexableRecyclerView#26]
304和309行代码重复
` mRecy = new RecyclerView(context);
        mIndexBar = new IndexBar(context);
        mRecy.setVerticalScrollBarEnabled(false);
        mRecy.setOverScrollMode(View.OVER_SCROLL_NEVER);
        addView(mRecy, new LayoutParams(LayoutParams.MATCH_PARENT, LayoutParams.MATCH_PARENT));

        mIndexBar = new IndexBar(context);
        mIndexBar.init(mBarBg, mBarTextColor, mBarFocusTextColor, mBarTextSize, mBarTextSpace);
        LayoutParams params = new LayoutParams((int) mBarWidth, LayoutParams.WRAP_CONTENT);
        params.gravity = Gravity.END | Gravity.CENTER_VERTICAL;
        addView(mIndexBar, params);`

**Comment by YoKeyword** [comment]
感谢提醒～    可以直接提PR啊 🙏～
