### ISSUE TITLE
mMDOverlay Background Tint 设置无效 

### ISSUE THREAD

**Issue by LibraZhu** [YoKeyword/IndexableRecyclerView#27]
有些机型出现mMDOverlay出现设置Background Tint无效的情况，现象是mMDOverlay只有白色的背景图片。测试机型华为CHM-CL00,android版本4.4.4

**Comment by YoKeyword** [comment]
已经修复了  1.0.8

之前天真认为`ViewCompat.setBackgroundTintList(mMDOverlay, ColorStateList.valueOf(color));`可以兼容全版本

现在改为`AppCompatTextView.setSupportBackgroundTintList()`了
