### ISSUE TITLE
楼主，谢谢你的开源，但是有个问题，就是怎么不要那个粘性Title。

### ISSUE THREAD

**Issue by liusilong** [YoKeyword/IndexableRecyclerView#28]
就是viewType == EntityWrapper.TYPE_TITLE，我在RealAdapter的getItemViewType(...)方法中直接返回EntityWrapper.TYPE_CONTENT发现不行，请问这个怎么办才可以。。。。谢谢！

**Comment by YoKeyword** [comment]
额，有种曲线方式...
把Title的布局高度设置为0...  😂

**Comment by liusilong** [comment]
谢谢楼主的回复，我明天试试…

**Comment by liusilong** [comment]
楼主，IndexableLayout类里面有方法获取排序后的集合吗？

**Comment by YoKeyword** [comment]
没有暴露出去， 因为StickyView的各种Title也是RecyclerView的子Item，所以排序后的Datas其实有包含这些Title， 暴露出去的意义不是很大，所以没有提供～

**Comment by liusilong** [comment]
有没有什么办法可以获取到呢？我看你是在transform方法中排的序，不过返回的是EntityWrapper类型的对象。

**Comment by YoKeyword** [comment]
为什么要排序后的数据呢？ 想不通啊...  点击后会返回对应的Item对象, position,原始position  应该足够使用了～
需求和库的功能差的比较大的话，可以考虑自己fork下修改或者自己简单实现的～

**Comment by liusilong** [comment]
因为现在有个这样的需求，就是让RecyclerView滚动到某个条目的位置，所以要获取到当前条目在排序之后的list中的位置~

**Comment by YoKeyword** [comment]
哦哦，这么说的话想起来，setDatas(datas, IndexCallback)的 Callback里会回调一个List<EntityWrapper<T>>对象， 这个就是排序完成后包含 Title、Header、Footer的数据集合；

不过刚发现，这个方法之前版本我错写成了回调List<T>对象 😓 

刚push了1.0.9版本，更新下就行了～

**Comment by liusilong** [comment]
楼主太给力了，赞十个！我明天试试看…
