### ISSUE TITLE
泛型写得不够好

### ISSUE THREAD

**Issue by qssq666123** [YoKeyword/IndexableRecyclerView#31]
holder得抢转。。

**Comment by YoKeyword** [comment]
嗯 确实不是很方便的～  

当然犹豫了下，使用的是现在自己强转的方式；

想不强转的话：Adapter就需要3个泛型了：
````java
class YourAdapter extends IndexableAdapter<YourEntity,TitleVH,ContentVH>{
}
````
这样使用者写起来感觉有点怪怪的，所以选用了 自己强转的方式，当然这个选择只是个人想法，可能确实欠妥   :)

**Comment by qssq666123** [comment]
@YoKeyword 嗯嗯,希望可以弄那种类似QQ音乐 里面的歌手 列表那种风格也就是只要一个title,而不是每一个都有title

**Comment by qssq666123** [comment]
为什么设置data没有回调呢？奇怪啊，你的demo是正常的，我这里就不正常了。我都断点调试了，就是回调没走

**Comment by qssq666123** [comment]
调试看了一下为什么观察者没注册成功

**Comment by qssq666123** [comment]
问题出来了，不过 逻辑要写严谨一点哦、比如观察者没注册 报错之类的

**Comment by qssq666123** [comment]
mFuture = mExecutorService.submit(new Runnable() {
            @Override
            public void run() {
                final ArrayList<EntityWrapper> datas = transform(mIndexableAdapter.getItems());
                if (datas == null) return;

                getSafeHandler().post(new Runnable() {
                    @Override
                    public void run() {
                        mRealAdapter.setDatas(datas);
                        mIndexBar.setDatas(mShowAllLetter, mRealAdapter.getItems());

                        if (mIndexableAdapter.getIndexCallback() != null) {
                            mIndexableAdapter.getIndexCallback().onFinished(datas);
                        }

                    }
                });
            }
        });
执行到这里 没法调试了，没有数据是不可能的。

**Comment by YoKeyword** [comment]
转#32；

最近个人闲余时间较少，开源方面重心在Fragmentation上，该库暂时没有更细致的维护打算，不过欢迎提PR，一起完善该库～
