### ISSUE TITLE
数据复用引发的问题怎么解决？望回复

### ISSUE THREAD

**Issue by liucaihua9** [YoKeyword/IndexableRecyclerView#39]
比如item项里有一个CheckBox，选中后，下拉，再返回，选中的状态就不见了，设置其他没有被选中的状态也会被选中，请问怎么解决？

**Comment by YoKeyword** [comment]
这个是ListView/RecyclerView复用引起的问题， 可以纪录选中的Item，然后渲染视图时判断当前显示的Item是否被标记为选中
