### ISSUE TITLE
请问支持GirdLayoutManager么

### ISSUE THREAD

**Issue by guodongAndroid** [YoKeyword/IndexableRecyclerView#40]

**Comment by YoKeyword** [comment]
我还没试过 😂    你可以试试，如果不行建议fork下代码修改； 当然如果兼容比较好的话提个PR就更好啦～

**Comment by guodongAndroid** [comment]
试了后发现，title原来也是一直item，所以K.O了。想再请教一个问题，IndexBar可以显示真实的索引，比如数据源中没有G开头的，索引中也不应该有G

**Comment by guodongAndroid** [comment]
抱歉，现在才看到一个方法可以设置真实索引。
