### ISSUE TITLE
貌似不支持水平的呀

### ISSUE THREAD

**Issue by qssq666123** [YoKeyword/IndexableRecyclerView#43]
ios特么做了一个水平的一行4个一直往下排的头像，服了他了，搞的我这边也要这么搞才行

**Comment by YoKeyword** [comment]
...

GridView的格式，现在应该不支持；  
最近工作比较忙，未来考虑会支持的

**Comment by guodongAndroid** [comment]
可以支持GridLayoutManager，我这边实现了

**Comment by qssq666123** [comment]
@guodongAndroid 能具体点吗？

**Comment by guodongAndroid** [comment]
我提交了一个PR，你可以去看看我fork的代码 @qssq666123

**Comment by YoKeyword** [comment]
感谢PR，已Merged， 1.2.0
