### ISSUE TITLE
貌似錯位了

### ISSUE THREAD

**Issue by SomnusWu** [YoKeyword/IndexableRecyclerView#47]
![Uploading bug5.png…]()
滑著滑著就出現了

**Comment by SomnusWu** [comment]
![bug6](https://cloud.githubusercontent.com/assets/7221064/23534705/aff42108-fff4-11e6-8eab-38b1ecaa8526.png)

**Comment by YoKeyword** [comment]
用下1.2.0，  1.1.1版本为了兼容一种特性导致的这个BUG

**Comment by guodongAndroid** [comment]
大哥，我用了mAdapter.notifyDataSetChanged();我全部的数据都是HeaderView，需要重新绑定么？ @YoKeyword

**Comment by YoKeyword** [comment]
@guodongAndroid  `mAdapter.notifyDataSetChanged()` 现在只会刷新修改时（不包括添加、删除）的数据；

周末我把这个notify机制完善下哈～

**Comment by guodongAndroid** [comment]
我提了个PR，你看一下哈~ @YoKeyword

**Comment by YoKeyword** [comment]
@SomnusWu 更新下1.2.3版本哈
