### ISSUE TITLE
有空么可以提供一下技术支持么

### ISSUE THREAD

**Issue by fangithubgithub** [YoKeyword/IndexableRecyclerView#49]

**Comment by guodongAndroid** [comment]
@fangithubgithub 有问题增加点描述啊

**Comment by fangithubgithub** [comment]
private List<CityEntity> initDatas() {
        List<CityEntity> list = new ArrayList<>();
        List<String> cityStrings = Arrays.asList(getResources().getStringArray(R.array.city_array));
        for (String item : cityStrings) {
            CityEntity cityEntity = new CityEntity();
            cityEntity.setName(item);
            list.add(cityEntity);
        }
        return list;
    }

**Comment by fangithubgithub** [comment]
怎么换我从后台获取到的数据

**Comment by fangithubgithub** [comment]
switch (msg.what) {
                case 0:
                    loadingWindow.cancel();
                    String str = (String) msg.obj;
                    java.lang.reflect.Type type = new TypeToken<VipBean>() {
                    }.getType();
                    VipBean rg = gson.fromJson(str, type);
                    if (rg.getCode() == 200) {

                      /////这块我怎么加到你的mdata里，
                        }

                    } else {
                        showToast(rg.getMsg());

                    }

**Comment by fangithubgithub** [comment]
拿到的数句怎么把你的死数据替换掉，

**Comment by guodongAndroid** [comment]
`
List<VipBean> mData = new ArrayList<>();
mData.add(rg);
mAdapter.setDatas(mData);
`

**Comment by fangithubgithub** [comment]
谢谢

**Comment by fangithubgithub** [comment]
自己憋出来了，刚才哈哈

**Comment by guodongAndroid** [comment]
OK，没问题的话就 close iss ，^_^

**Comment by fangithubgithub** [comment]
好的
