### ISSUE TITLE
Header 部分如何以GridView 方式显示

### ISSUE THREAD

**Issue by wuyajun7** [YoKeyword/IndexableRecyclerView#57]
添加一个IndexableHeaderAdapter 此部分如何以GridView 方式显示

**Comment by bozhai** [comment]
同问
我开了一个新的issues，还有一些其他的问题

**Comment by YoKeyword** [comment]
@wuyajun7  
直接滑动控件嵌套滑动控件官方并不推荐，Header的内容不多的情况下，暂时建议使用一个ViewGroup布局来添加Item；或者fork下代码通过RecyclerView的ItemType来添加Header
