### ISSUE TITLE
发现动态删除和添加（重新设置数据）stickyHeader更新不及时的解决办法

### ISSUE THREAD

**Issue by D1191860939** [YoKeyword/IndexableRecyclerView#61]
在IndexableLayout.java中的onDataChanged()方法里：
if (mIndexableAdapter.getIndexCallback() != null) {
                    mIndexableAdapter.getIndexCallback().onFinished(datas);
                }
的后面添加如下代码：
`int firstItemPosition = mLayoutManager.findFirstVisibleItemPosition();

                if (!mSticyEnable) return;
                ArrayList<EntityWrapper> list = mRealAdapter.getItems();
                if (firstItemPosition >= 0) {
                    if (mStickyViewHolder != null && list.size() > firstItemPosition) {
                        EntityWrapper wrapper = list.get(firstItemPosition);
                        String wrapperTitle = wrapper.getIndexTitle();

                        // hide -> show
                        if (wrapperTitle == null && mStickyViewHolder.itemView.getVisibility() == VISIBLE || wrapper.getItemType() == EntityWrapper.TYPE_CUSTOMER_FOOTER) {
                            mStickyTitle = null;
                            mStickyViewHolder.itemView.setVisibility(INVISIBLE);
                        } else {
                            stickyNewViewHolder(wrapperTitle);
                        }
                    }
                }`

**Comment by YoKeyword** [comment]
感谢哈， v1.2.4已经添加，下次可以直接提PR  🍺 :)
