### ISSUE TITLE
用你那个类似于城市列表选择和联系人列表，多音字有点问题

### ISSUE THREAD

**Issue by GitACDreamer** [YoKeyword/IndexableRecyclerView#63]
例如： 重庆市XXX有限公司，他会归类到‘Z’而不是'C'
            还有姓氏 例如 单雄信  ‘Shan’ 这个会归类到‘Dan’
            你那个demo城市选择列表里面重庆市没有问题。
            像这类问题如何解决？
` // 添加中文城市词典
  Pinyin.init(Pinyin.newConfig().with(CnCityDict.getInstance());` 是否需要添加这句？

**Comment by YoKeyword** [comment]
> 2、多音字处理

> 多音字需要手动处理: 例如城市排序时, 拼音转化库默认重庆为zhongqing, 对于这种情况你需要手动将源数据的 '重庆' 修改 为'#chongqing#重庆', 库会根据正则表达式进行对应的辨别处理(即 #多音字拼音#汉字 的格式)

库中提供了上述方法，  我刚看了tinyPinyin库，发现它在近期提供了你所说的方法来解决多音字，应该也是可以的 :)

**Comment by SheepYang1993** [comment]
好像还是不行，曾会出现在C
