### ISSUE TITLE
建议预留出来一些接口 供外界扩展，recyclerview 的灵活性都整没了。

### ISSUE THREAD

**Issue by MirkoWu** [YoKeyword/IndexableRecyclerView#74]
你这里相当于把header 和footer 定死了，整个列表统一的样式，setSpanSizeLookup（）也不可重写，recyclerview 的灵活性都没了，改都没法改，建议预留出来一些接口 供外界扩展。

**Comment by YoKeyword** [comment]
这库是针对选择城市、联系人等字母索引使用场景的快速解决方案，满足一般场景下的需求

当然如你所说，header footer灵活度确实不够,目前只能放View，这个库目前没精力维护，对于特殊需求可以自己fork拓展，如果可能，欢迎PR ：)
