### ISSUE TITLE
索引有重复的时候，会出现顶部悬浮title默认为重复索引中指向的第一个title。已修改

### ISSUE THREAD

**Issue by yygutn** [YoKeyword/IndexableRecyclerView#9]
`
private void initInvalidate(int firstVisibleItem, int i) {

        mCurrentScrollPos = firstVisibleItem;
        if (mScrollState != -1) {
            mSelectionPos = i;

            String indexTitle = getIndexTitle(i, firstVisibleItem);
            mOnIndexSelectedListener.onSelection(mSelectionPos, indexTitle);
        }

        invalidate();
    } 

`
/**
     * 修改相同索引，StickIndex出现的title显示异常，
     * @param position 根据IndexBar索引字体获取的title位置，当title重复时候，会默认获取第一个title，而不是真实的title
     * @param firstVisibleItem 顶部显示元素的位置
     * @return
     */

`

    private String getIndexTitle(int position, int firstVisibleItem) {

        if (mAdapter == null) return "";
        SparseArray<String> map = mAdapter.getTitleMap();
        int len = map.size();
        if (firstVisibleItem >= map.keyAt(len - 1)) {
            return map.get(map.keyAt(len - 1));
        }
        for (int i = 0; i < len - 1; i++) {
            if (firstVisibleItem >= map.keyAt(i) && firstVisibleItem < map.keyAt(i + 1)) {
                return map.get(map.keyAt(i));
            }
        }
        if (position >= size) {
            return mIndex.get(position);
        } else {
            return map.get(map.keyAt(position));
        }
    }

`

**Comment by YoKeyword** [comment]
抱歉，一直没注意这个issue...  没明白你的意思～    能上张图片最好～

**Comment by yygutn** [comment]
就是N组常用，命名叫 常用A....常用Z等，下拉过程中，常用A会一直悬浮在最上面

**Comment by YoKeyword** [comment]
悬浮的Sticky不是除了热门这种header之外都是显示 ABCD这种吗～  咋会显示“常用A”，能有张图片或图片链接最好啦～ 还有使用最新版看下 这个问题是否被解决了～

**Comment by YoKeyword** [comment]
进行非常大幅度的重构；从ListView更改为RecyclerView的实现
性能优化，更易使用的API，更易拓展的HeaderView等等   :)
